Crafting system
TK-786/Signs-Of-Survival-Source pull request #57
Opened 2024-12-17 02:03 UTC by Hemat02

Please check functionality. Crafting system fully implemented.

2024-12-17 23:52 UTC, TK-786 commented on Assets/Scripts/Inventory/Crafting/AdranalinePotion.cs
> +public class AdranalinePotion : MonoBehaviour
Adrenaline*

2024-12-17 23:54 UTC, TK-786 commented on Assets/Scripts/Inventory/InventoryManager.cs
> +    public CraftingManager craftingManager;
I don't think it needs to be exposed @Hemat02?

2024-12-17 23:56 UTC, TK-786 commented on Assets/Scripts/Inventory/InventoryManager.cs
> +        if (Input.GetKeyDown(KeyCode.E))
could be moved to pickup script potentially

2024-12-17 23:58 UTC, TK-786 commented on Assets/Scripts/Monsters/Item.cs
> +    public string itemName;
there are getters at the bottom of the file. Didn't need to be public

2024-12-17 23:59 UTC, TK-786 requested changes
Address comments, but seems good

2024-12-18 17:25 UTC, HamidH3 approved these changes
Works nice, well done.

2024-12-18 17:54 UTC, TK-786 approved these changes

2024-12-18 17:55 UTC, merged